name: uk259
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - tensorflow
  - jupyter
  - seaborn
  - ipykernel
  - ipympl
  - pydot 
  - graphviz 
  #- nodejs=16.*


# conda activate uk259
# conda env update --file environment.yml --prune