name: uk259_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - tensorflow
  - jupyter
  - seaborn
  - ipykernel
  - ipympl
  - pydot 
  - graphviz 